- name: Using IBM Storage Virtualize collection
  hosts: localhost
  tasks:
    - name: Gather info from Storage
      ibm.storage_virtualize.ibm_svc_info:
        clustername: 172.23.76.135
        username: superuser
        password: "passw0rd"
    - name: Run svctask
      ibm.storage_virtualize.ibm_svctask_command:
        command: ["svctask mkvdisk -name vo11 -mdiskgrp pool0 -easytier off -size 1 -unit gb"]
        clustername: "{{172.23.76.135}}"
        username: "{{ superuser }}"
        password: "{{passw0rd}}"
        log_path: /root/Documents/ansible.log
